/*
 *******************************************************************************
 *
 * Copyright (C) 2016-2018 Dialog Semiconductor.
 * This computer program includes Confidential, Proprietary Information
 * of Dialog Semiconductor. All Rights Reserved.
 *
 *******************************************************************************
 */

#define DIALOG_WEARABLES_SERVICE_SCAN_UUID                  @"2ea7"
#define DIALOG_IBEACON_ASSET_UUID                           @"5ec6ed9b-0025-139a-cc42-011b93de5c58"

#define DIALOG_WEARABLES_SERVICE                            @"2ea78970-7d44-44bb-b097-26183f402400"
#define DIALOG_WEARABLES_CHARACTERISTIC_ACCELEROMETER       @"2ea78970-7d44-44bb-b097-26183f402401"
#define DIALOG_WEARABLES_CHARACTERISTIC_GYROSCOPE           @"2ea78970-7d44-44bb-b097-26183f402402"
#define DIALOG_WEARABLES_CHARACTERISTIC_MAGNETOMETER        @"2ea78970-7d44-44bb-b097-26183f402403"
#define DIALOG_WEARABLES_CHARACTERISTIC_BAROMETER           @"2ea78970-7d44-44bb-b097-26183f402404"
#define DIALOG_WEARABLES_CHARACTERISTIC_HUMIDITY            @"2ea78970-7d44-44bb-b097-26183f402405"
#define DIALOG_WEARABLES_CHARACTERISTIC_TEMPERATURE         @"2ea78970-7d44-44bb-b097-26183f402406"
#define DIALOG_WEARABLES_CHARACTERISTIC_SENSOR_FUSION       @"2ea78970-7d44-44bb-b097-26183f402407"
#define DIALOG_WEARABLES_CHARACTERISTIC_MULTI_SENSOR        @"2ea78970-7d44-44bb-b097-26183f402410"
#define DIALOG_WEARABLES_CHARACTERISTIC_FEATURES            @"2ea78970-7d44-44bb-b097-26183f402408"
#define DIALOG_WEARABLES_CHARACTERISTIC_CONTROL             @"2ea78970-7d44-44bb-b097-26183f402409"
#define DIALOG_WEARABLES_CHARACTERISTIC_CONTROL_NOTIFY      @"2ea78970-7d44-44bb-b097-26183f40240a"

#define DIALOG_WEARABLES_COMMAND_CONFIGURATION_STOP                 0
#define DIALOG_WEARABLES_COMMAND_CONFIGURATION_START                1
#define DIALOG_WEARABLES_COMMAND_CONFIGURATION_READ_NV              2
#define DIALOG_WEARABLES_COMMAND_CONFIGURATION_RESET_TO_DEFAULTS    3
#define DIALOG_WEARABLES_COMMAND_CONFIGURATION_STORE_NV             4
#define DIALOG_WEARABLES_COMMAND_CALIBRATION_STORE_NV               5
#define DIALOG_WEARABLES_COMMAND_CONFIGURATION_RUNNING_STATE        6
#define DIALOG_WEARABLES_COMMAND_CALIBRATION_RESET_TO_DEFAULTS      7
#define DIALOG_WEARABLES_COMMAND_CONFIGURATION_WRITE                10
#define DIALOG_WEARABLES_COMMAND_CONFIGURATION_READ                 11
#define DIALOG_WEARABLES_COMMAND_CALIBRATION_SFL_COEFFICIENTS_WRITE 12
#define DIALOG_WEARABLES_COMMAND_CALIBRATION_SFL_COEFFICIENTS_READ  13
#define DIALOG_WEARABLES_COMMAND_CALIBRATION_COEFFICIENTS_WRITE     14
#define DIALOG_WEARABLES_COMMAND_CALIBRATION_COEFFICIENTS_READ      15
#define DIALOG_WEARABLES_COMMAND_CALIBRATION_CONTROL_WRITE          16
#define DIALOG_WEARABLES_COMMAND_CALIBRATION_CONTROL_READ           17
#define DIALOG_WEARABLES_COMMAND_CALIBRATION_ACCELEROMETER_START    18
#define DIALOG_WEARABLES_COMMAND_CALIBRATION_SET_MODES              19
#define DIALOG_WEARABLES_COMMAND_CALIBRATION_READ_MODES             20
#define DIALOG_WEARABLES_COMMAND_READ_FEATURES                      21
#define DIALOG_WEARABLES_COMMAND_READ_VERSION                       22
#define DIALOG_WEARABLES_COMMAND_START_LED_BLINK                    23
#define DIALOG_WEARABLES_COMMAND_STOP_LED_BLINK                     24
#define DIALOG_WEARABLES_COMMAND_PROXIMITY_HYSTERESIS_WRITE         25
#define DIALOG_WEARABLES_COMMAND_PROXIMITY_HYSTERESIS_READ          26
#define DIALOG_WEARABLES_COMMAND_CALIBRATION_COMPLETE               27
#define DIALOG_WEARABLES_COMMAND_PROXIMITY_CALIBRATION              28

#define MULTI_SENSOR_REPORT_PREAMBLE 0xA5
#define SENSOR_REPORT_LENGTH_SINGLE  7
#define SENSOR_REPORT_LENGTH_3D      9
#define SENSOR_REPORT_LENGTH_4D      11
#define SENSOR_REPORT_ACCELEROMETER_LENGTH       SENSOR_REPORT_LENGTH_3D
#define SENSOR_REPORT_GYROSCOPE_LENGTH           SENSOR_REPORT_LENGTH_3D
#define SENSOR_REPORT_MAGNETOMETER_LENGTH        SENSOR_REPORT_LENGTH_3D
#define SENSOR_REPORT_PRESSURE_LENGTH            SENSOR_REPORT_LENGTH_SINGLE
#define SENSOR_REPORT_HUMIDITY_LENGTH            SENSOR_REPORT_LENGTH_SINGLE
#define SENSOR_REPORT_TEMPERATURE_LENGTH         SENSOR_REPORT_LENGTH_SINGLE
#define SENSOR_REPORT_SENSOR_FUSION_LENGTH       SENSOR_REPORT_LENGTH_4D
#define SENSOR_REPORT_AMBIENT_LIGHT_LENGTH       SENSOR_REPORT_LENGTH_SINGLE
#define SENSOR_REPORT_PROXIMITY_LENGTH           SENSOR_REPORT_LENGTH_SINGLE
#define SENSOR_REPORT_GAS_LENGTH                 SENSOR_REPORT_LENGTH_SINGLE
#define SENSOR_REPORT_AIR_QUALITY_LENGTH         SENSOR_REPORT_LENGTH_SINGLE
#define SENSOR_REPORT_BUTTON_LENGTH              SENSOR_REPORT_LENGTH_SINGLE
#define SENSOR_REPORT_VELOCITY_DELTA_LENGTH      SENSOR_REPORT_LENGTH_3D
#define SENSOR_REPORT_EULER_ANGLE_DELTA_LENGTH   SENSOR_REPORT_LENGTH_3D
#define SENSOR_REPORT_QUATERNION_DELTA_LENGTH    SENSOR_REPORT_LENGTH_4D

enum {
    SENSOR_REPORT_ACCELEROMETER = 1,
    SENSOR_REPORT_GYROSCOPE = 2,
    SENSOR_REPORT_MAGNETOMETER = 3,
    SENSOR_REPORT_PRESSURE = 4,
    SENSOR_REPORT_HUMIDITY = 5,
    SENSOR_REPORT_TEMPERATURE = 6,
    SENSOR_REPORT_SENSOR_FUSION = 7,
    SENSOR_REPORT_AMBIENT_LIGHT = 9,
    SENSOR_REPORT_PROXIMITY = 10,
    SENSOR_REPORT_GAS = 11,
    SENSOR_REPORT_AIR_QUALITY = 12,
    SENSOR_REPORT_BUTTON = 13,
    SENSOR_REPORT_VELOCITY_DELTA = 14,
    SENSOR_REPORT_EULER_ANGLE_DELTA = 15,
    SENSOR_REPORT_QUATERNION_DELTA = 16,
};

enum {
    SENSOR_TYPE_ACCELEROMETER = 0,
    SENSOR_TYPE_GYROSCOPE = 1,
    SENSOR_TYPE_MAGNETOMETER = 2,
};

enum {
    CALIBRATION_MODE_NONE = 0,
    CALIBRATION_MODE_STATIC = 1,
    CALIBRATION_MODE_CONTINUOUS_AUTO = 2,
    CALIBRATION_MODE_ONE_SHOT_AUTO = 3,
};

enum {
    CALIBRATION_AUTO_MODE_BASIC = 0,
    CALIBRATION_AUTO_MODE_SMART = 1,
};

enum {
    IOT_SENSORS_FEATURE_NONE = 0,
    IOT_SENSORS_FEATURE_ACCELEROMETER = 1,
    IOT_SENSORS_FEATURE_GYROSCOPE = 2,
    IOT_SENSORS_FEATURE_MAGNETOMETER = 3,
    IOT_SENSORS_FEATURE_PRESSURE = 4,
    IOT_SENSORS_FEATURE_HUMIDITY = 5,
    IOT_SENSORS_FEATURE_TEMPERATURE = 6,
    IOT_SENSORS_FEATURE_AMBIENT_LIGHT = 7,
    IOT_SENSORS_FEATURE_PROXIMITY = 8,
    IOT_SENSORS_FEATURE_BUTTON = 9,
    IOT_SENSORS_FEATURE_RAW_GAS = 10,
    IOT_SENSORS_FEATURE_PROXIMITY_CALIBRATION = 11,
    IOT_SENSORS_FEATURE_SENSOR_FUSION = 64,
    IOT_SENSORS_FEATURE_INTEGRATION_ENGINE = 65,
    IOT_SENSORS_FEATURE_AIR_QUALITY = 66,
};

#define UIColorWithRGB(rgb) [UIColor colorWithRed:(((rgb)>>16)&0xff)/255. green:(((rgb)>>8)&0xff)/255. blue:((rgb)&0xff)/255. alpha:1.]
